### ISSUE TITLE
Extract Test related CLI commands

### ISSUE THREAD

**Issue by wintondeshong** [AndcultureCode/AndcultureCode.DotnetReact.Boilerplate#14]
Extract the test related CLI commands in the project to the `AndcultureCode.CSharp.Cli` package

- [ ] TestCommand
- [ ] TestDatabaseCommand
- [ ] TestDatabaseMigrateCommand

**Comment by dylanjustice** [comment]
@wintondeshong Would you prefer it to be set up with parallelized integration test databases by fixture? Makes for a pretty snappy integration test suite.

**Comment by andCulture** [comment]
That’d be great 👍🏻

**Comment by dylanjustice** [comment]
Do we still find it useful to include these commands in the CSharp.Cli package? I can pull this issue to that repo specifically.

**Comment by brandongregoryscott** [comment]
@dylanjustice I would say so

**Comment by dylanjustice** [comment]
Migrated to https://github.com/AndcultureCode/AndcultureCode.CSharp.Cli/issues/5
