### ISSUE TITLE
Add `.npmrc` file to make npm always use exact versions

### ISSUE THREAD

**Issue by mrjones2014** [AndcultureCode/AndcultureCode.DotnetReact.Boilerplate#51]
Using version ranges (i.e. `^1.0.0` which means "anything 1.0.0 or newer) is dangerous. We can add an `.npmrc` that will tell npm to install exact versions by default.
https://docs.npmjs.com/misc/config

**Comment by mrjones2014** [comment]
contents just has to be 
```
save-exact=true
```

**Comment by wintondeshong** [comment]
@mrjones2014 happy to assign to you if you want the credit :)

**Comment by mrjones2014** [comment]
@wintondeshong I think I have permission to assign myself, but I can definitely take care of it!
